### ISSUE TITLE
Single URL errors

### ISSUE THREAD

**Issue by znre** [sensepost/gowitness#66]
**Describe the bug**
I am experiencing two errors when trying to run gowitness. One error says something about a "context deadline exceeded", and the other is "failed to save screenshot buffer"

**To Reproduce**
On the command line, type:
1. gowitness single https://tesla.com
2. gowitness single https://reddit.com

**Expected behavior**
Screenshots will be taken of the site.

**Screenshots**
![image](https://user-images.githubusercontent.com/70197545/93950178-670b0d80-fd75-11ea-945c-c60ac183c892.png)

![image](https://user-images.githubusercontent.com/70197545/93950190-6f634880-fd75-11ea-88fe-94321ad39e26.png)

**Version Information:**
 - OS: Kali GNU/Linux Rolling x86_64
 - gowitness: 2.0.0

**Comment by randomactsofsecurity** [comment]
Ran into this issue as well recently, think the issue may be from the instantiation of the http transport in chrome.go missing some of the defaults?

`transport := http.DefaultTransport.(*http.Transport).Clone()`

Seems to fix the issue with a shallow copy, but need to test it out a bit more against more assets in comparison to the old version.

**Comment by leonjza** [comment]
I can replicate this on Kali, but works fine on macOS. 🤔

**Comment by leonjza** [comment]
So there are two problems here. For the error related to reddit a fix is incoming shortly. As for tesla.com, there seems to be weirdness in how the server responds based on the `User-Agent` and `Connection` headers. Still debugging this.

**Comment by leonjza** [comment]
I am happy I fixed the reddit example (thanks for reporting @znre). As for tesla.com, the preflight request fails with this request.

![image](https://user-images.githubusercontent.com/1148127/94014898-75c0e700-fdac-11ea-9944-7085672df90d.png)

For the sake of copy/paste.

```GET / HTTP/1.1
Host: www.tesla.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Referer: https://tesla.com
Accept-Encoding: gzip, deflate
Connection: close

```

Change the `User-Agent` to `curl`, and it will work, or `Connection` to `keep-alive` and it will sometimes work. So the question is I guess, does it make sense to set the UA in the preflight as well? In my mind it does, but we have this interesting case now.

**Comment by artemidas** [comment]
Hey there, any updates on this one? It seems that `gowitness single https://www.tesla.com/es_ES/` works just fine. I'm from Spain by the way 😉

**Comment by lyonys** [comment]
@leonjza I am still facing the same issues in the latest build. gowitness fails to create a local 'screenshot' folder. I think we can change it to use mkdirall instead of mkdir and it would resolve the issue.

https://stackoverflow.com/questions/37932551/mkdir-if-not-exists-using-golang

**Comment by leonjza** [comment]
@lyonys are you providing a path that is deeper than 1 directory?

**Comment by xingshanghe** [comment]
try the cmd : gowitness single -u https://tesla.com

**Comment by leonjza** [comment]
Closing this for now. Looks like the tesla.com example works at the moment.
